import type { MuscleFacts } from "../../muscleFacts";

/** Study metadata for thigh, hip and deep posterior-knee muscles. */
export interface UpperLegMuscleFact extends MuscleFacts {
  name: string;
  group: string;
  description: string;
}

const source = (title: string, url: string) => ({ title, url });
const loyola = source("Loyola University Chicago · Lower extremity muscle table", "https://www.stritch.luc.edu/lumen/meded/grossanatomy/homepage/muscletables/lowerextremitymuscletable.pdf");
const ncbiThigh = source("NCBI Bookshelf · Thigh muscles", "https://www.ncbi.nlm.nih.gov/books/NBK482445/");
const ncbiGluteus = source("NCBI Bookshelf · Gluteus maximus muscle", "https://www.ncbi.nlm.nih.gov/books/NBK538193/");
const ncbiPiriformis = source("NCBI Bookshelf · Piriformis muscle", "https://www.ncbi.nlm.nih.gov/books/NBK519497/");
const ncbiObturator = source("NCBI Bookshelf · Obturator muscles", "https://www.ncbi.nlm.nih.gov/books/NBK589636/");
const ncbiPopliteus = source("NCBI Bookshelf · Popliteus muscle", "https://www.ncbi.nlm.nih.gov/books/NBK526084/");
const anterior = "Anterior thigh";
const medial = "Medial thigh";
const posterior = "Posterior thigh";
const gluteal = "Gluteal and deep hip";

export const upperLegFacts: Record<string, UpperLegMuscleFact> = {
  "rectus-femoris": { name: "Rectus femoris", group: "Quadriceps", description: "The superficial, biarticular central quadriceps muscle.", origin: "Straight head from the anterior inferior iliac spine; reflected head from the ilium just superior to the acetabulum.", insertion: "Quadriceps tendon to the patella, continuing through the patellar ligament to the tibial tuberosity.", action: "Extends the knee and flexes the hip.", innervation: "Femoral nerve (L2–L4).", bloodSupply: "Lateral circumflex femoral and profunda femoris arteries.", references: [loyola, ncbiThigh] },
  "vastus-lateralis": { name: "Vastus lateralis", group: "Quadriceps", description: "The large lateral quadriceps muscle forming the outer thigh.", origin: "Greater trochanter, gluteal tuberosity and lateral lip of the linea aspera.", insertion: "Quadriceps tendon to the patella, continuing through the patellar ligament to the tibial tuberosity.", action: "Extends the knee.", innervation: "Femoral nerve (L2–L4).", bloodSupply: "Lateral circumflex femoral and profunda femoris arteries.", references: [loyola, ncbiThigh] },
  "vastus-medialis": { name: "Vastus medialis", group: "Quadriceps", description: "The medial quadriceps muscle along the inner femur.", origin: "Intertrochanteric line and medial lip of the linea aspera.", insertion: "Quadriceps tendon to the patella, continuing through the patellar ligament to the tibial tuberosity.", action: "Extends the knee and contributes medial patellar stabilization.", innervation: "Femoral nerve (L2–L4).", bloodSupply: "Femoral, profunda femoris and superior medial genicular branches of the popliteal artery.", references: [loyola, ncbiThigh] },
  "vastus-intermedius": { name: "Vastus intermedius", group: "Quadriceps · deep", description: "The deep quadriceps muscle beneath rectus femoris.", origin: "Anterior and lateral surfaces of the proximal and middle femoral shaft.", insertion: "Quadriceps tendon to the patella, continuing through the patellar ligament to the tibial tuberosity.", action: "Extends the knee.", innervation: "Femoral nerve (L2–L4).", bloodSupply: "Lateral circumflex femoral and profunda femoris arteries.", references: [loyola, ncbiThigh] },
  sartorius: { name: "Sartorius", group: anterior, description: "A long strap muscle crossing the anterior thigh obliquely.", origin: "Anterior superior iliac spine and the notch immediately inferior to it.", insertion: "Superior medial tibia as part of the pes anserinus.", action: "Flexes, abducts and laterally rotates the hip; flexes the knee.", innervation: "Femoral nerve (L2–L4).", bloodSupply: "Muscular branches of the femoral artery.", references: [loyola, ncbiThigh] },
  "tensor-fasciae-latae": { name: "Tensor fasciae latae", group: "Gluteal abductors", description: "A short anterolateral hip muscle that tensions the iliotibial tract.", origin: "Anterior superior iliac spine and adjacent anterior iliac crest.", insertion: "Iliotibial tract, which attaches distally at the lateral tibial condyle.", action: "Flexes, abducts and medially rotates the hip; helps keep the knee extended.", innervation: "Superior gluteal nerve (L4–S1).", bloodSupply: "Ascending branch of the lateral circumflex femoral artery.", references: [loyola, ncbiThigh] },
  "gluteus-maximus": { name: "Gluteus maximus", group: gluteal, description: "The large superficial gluteal muscle and powerful hip extensor.", origin: "Ilium posterior to the posterior gluteal line, dorsal sacrum and coccyx, sacrotuberous ligament and related thoracolumbar fascia.", insertion: "Most fibers enter the iliotibial tract; deep fibers attach to the gluteal tuberosity of the femur.", action: "Extends and laterally rotates the hip; upper fibers assist abduction.", innervation: "Inferior gluteal nerve (L5–S2).", bloodSupply: "Primarily the inferior gluteal artery, with contributions from the superior gluteal artery.", references: [loyola, ncbiGluteus] },
  "gluteus-medius": { name: "Gluteus medius", group: gluteal, description: "A broad lateral hip abductor that steadies the pelvis during gait.", origin: "Lateral surface of the ilium between the anterior and posterior gluteal lines.", insertion: "Lateral surface of the greater trochanter of the femur.", action: "Abducts and medially rotates the hip; stabilizes the pelvis on the weight-bearing leg.", innervation: "Superior gluteal nerve (L4–S1).", bloodSupply: "Superior gluteal artery.", references: [loyola, ncbiGluteus] },
  "gluteus-minimus": { name: "Gluteus minimus", group: gluteal, description: "The deepest of the three gluteal muscles and a hip abductor.", origin: "Lateral surface of the ilium between the anterior and inferior gluteal lines.", insertion: "Anterior surface of the greater trochanter of the femur.", action: "Abducts and medially rotates the hip; stabilizes the pelvis during single-leg stance.", innervation: "Superior gluteal nerve (L4–S1).", bloodSupply: "Main trunk and deep branch of the superior gluteal artery.", references: [loyola, ncbiGluteus] },
  iliacus: { name: "Iliacus", group: anterior, description: "The iliac-fossa component of the iliopsoas hip flexor.", origin: "Superior two-thirds of the iliac fossa, inner iliac crest, ala of the sacrum and anterior sacroiliac ligaments.", insertion: "Lesser trochanter and adjacent femoral shaft through the iliopsoas tendon.", action: "Flexes the hip and stabilizes the hip joint, acting with psoas major.", innervation: "Femoral nerve (primarily L2–L3).", bloodSupply: "Iliac branches of the iliolumbar artery.", references: [loyola, ncbiThigh] },
  "psoas-major": { name: "Psoas major", group: anterior, description: "The lumbar component of the iliopsoas, descending to the lesser trochanter.", origin: "Sides of the T12–L5 vertebral bodies and intervening discs, plus the transverse processes of the lumbar vertebrae.", insertion: "Lesser trochanter of the femur through the iliopsoas tendon.", action: "Flexes the hip; with the limb fixed, flexes or laterally bends the trunk and helps balance it.", innervation: "Anterior rami of the lumbar plexus, chiefly L1–L3.", bloodSupply: "Lumbar branches of the iliolumbar artery.", references: [loyola, ncbiThigh] },
  pectineus: { name: "Pectineus", group: medial, description: "A short superior medial-thigh muscle at the floor of the femoral triangle.", origin: "Pecten of the pubis and superior ramus of the pubis.", insertion: "Pectineal line of the femur.", action: "Adducts and flexes the hip.", innervation: "Usually the femoral nerve; an obturator contribution may occur.", bloodSupply: "Medial circumflex femoral and obturator arteries.", references: [loyola, ncbiThigh] },
  "adductor-longus": { name: "Adductor longus", group: medial, description: "A superficial, fan-shaped medial-thigh adductor.", origin: "Body of the pubis inferior to the pubic crest.", insertion: "Middle third of the linea aspera of the femur.", action: "Adducts the hip and assists hip flexion.", innervation: "Anterior division of the obturator nerve (L2–L4).", bloodSupply: "Profunda femoris and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  "adductor-brevis": { name: "Adductor brevis", group: medial, description: "A short medial-thigh adductor deep to adductor longus.", origin: "Body and inferior ramus of the pubis.", insertion: "Pectineal line and proximal linea aspera of the femur.", action: "Adducts the hip and weakly flexes it.", innervation: "Obturator nerve; anterior or posterior division can predominate.", bloodSupply: "Profunda femoris, medial circumflex femoral and obturator arteries.", references: [loyola, ncbiThigh] },
  "adductor-magnus": { name: "Adductor magnus", group: medial, description: "A large medial-thigh muscle with adductor and hamstring portions.", origin: "Inferior pubic ramus and ramus of the ischium; the hamstring portion also arises from the ischial tuberosity.", insertion: "Gluteal tuberosity, linea aspera and medial supracondylar line; hamstring portion reaches the adductor tubercle.", action: "Adducts the hip; adductor fibers assist flexion while hamstring fibers extend the hip.", innervation: "Obturator nerve for the adductor portion; tibial division of the sciatic nerve for the hamstring portion.", bloodSupply: "Femoral, profunda femoris and obturator arteries, including perforating branches.", references: [loyola, ncbiThigh] },
  gracilis: { name: "Gracilis", group: medial, description: "A slender medial-thigh muscle that crosses both the hip and knee.", origin: "Body and inferior ramus of the pubis.", insertion: "Superior medial tibia as part of the pes anserinus.", action: "Adducts the hip; flexes the knee and medially rotates the leg.", innervation: "Obturator nerve (L2–L3).", bloodSupply: "Profunda femoris and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  "biceps-femoris-long-head": { name: "Biceps femoris · long head", group: posterior, description: "The biarticular, tibial-nerve component of the lateral hamstring.", origin: "Ischial tuberosity, sharing a proximal tendon with semitendinosus.", insertion: "Lateral side of the head of the fibula, with an expansion toward the lateral tibia.", action: "Flexes and laterally rotates the knee; extends the hip.", innervation: "Tibial division of the sciatic nerve (L5–S2).", bloodSupply: "Perforating branches of profunda femoris, inferior gluteal and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  "biceps-femoris-short-head": { name: "Biceps femoris · short head", group: posterior, description: "The single-joint, common-fibular component of the lateral hamstring.", origin: "Linea aspera and lateral supracondylar line of the femur.", insertion: "Lateral side of the head of the fibula, joining the long-head tendon.", action: "Flexes and laterally rotates the knee.", innervation: "Common fibular division of the sciatic nerve.", bloodSupply: "Perforating branches of profunda femoris, inferior gluteal and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  semitendinosus: { name: "Semitendinosus", group: posterior, description: "A superficial medial hamstring with a long distal tendon.", origin: "Ischial tuberosity.", insertion: "Superior medial tibia as part of the pes anserinus.", action: "Extends the hip; flexes the knee and medially rotates the leg.", innervation: "Tibial division of the sciatic nerve (L5–S2).", bloodSupply: "Perforating branches of profunda femoris and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  semimembranosus: { name: "Semimembranosus", group: posterior, description: "A broad, deep medial hamstring muscle.", origin: "Ischial tuberosity.", insertion: "Posterior part of the medial tibial condyle, with expansions into the posterior knee capsule.", action: "Extends the hip; flexes the knee and medially rotates the leg.", innervation: "Tibial division of the sciatic nerve (L5–S2).", bloodSupply: "Perforating branches of profunda femoris and medial circumflex femoral arteries.", references: [loyola, ncbiThigh] },
  "obturator-externus": { name: "Obturator externus", group: medial, description: "A deep medial-hip muscle that wraps around the ischium to the femur.", origin: "Margins of the obturator foramen and external surface of the obturator membrane.", insertion: "Trochanteric fossa of the femur.", action: "Laterally rotates and adducts the hip; stabilizes the femoral head in the acetabulum.", innervation: "Obturator nerve (posterior division).", bloodSupply: "Medial circumflex femoral and obturator arteries.", references: [loyola, ncbiObturator] },
  "obturator-internus": { name: "Obturator internus", group: gluteal, description: "A deep external rotator whose tendon exits the pelvis through the lesser sciatic foramen.", origin: "Pelvic surface of the obturator membrane and surrounding margins of the obturator foramen.", insertion: "Medial surface of the greater trochanter through a tendon shared with the gemelli.", action: "Laterally rotates the extended hip, abducts the flexed hip and stabilizes the femoral head.", innervation: "Nerve to obturator internus (L5–S2).", bloodSupply: "Internal pudendal and obturator arteries.", references: [loyola, ncbiObturator] },
  "superior-gemellus": { name: "Superior gemellus", group: gluteal, description: "A small external rotator above the obturator internus tendon.", origin: "Outer surface of the ischial spine.", insertion: "Medial surface of the greater trochanter through the obturator internus tendon.", action: "Laterally rotates the extended hip and stabilizes the femoral head.", innervation: "Nerve to obturator internus.", bloodSupply: "Inferior gluteal and internal pudendal arteries.", references: [loyola, ncbiObturator] },
  "inferior-gemellus": { name: "Inferior gemellus", group: gluteal, description: "A small external rotator below the obturator internus tendon.", origin: "Upper part of the ischial tuberosity.", insertion: "Medial surface of the greater trochanter through the obturator internus tendon.", action: "Laterally rotates the extended hip and stabilizes the femoral head.", innervation: "Nerve to quadratus femoris.", bloodSupply: "Medial circumflex femoral artery.", references: [loyola, ncbiObturator] },
  "quadratus-femoris": { name: "Quadratus femoris", group: gluteal, description: "A rectangular deep hip muscle and powerful short external rotator.", origin: "Lateral border of the ischial tuberosity.", insertion: "Quadrate tubercle and adjacent intertrochanteric crest of the femur.", action: "Laterally rotates and assists adduction of the hip.", innervation: "Nerve to quadratus femoris (L4–S1).", bloodSupply: "Medial circumflex femoral artery.", references: [loyola, ncbiObturator] },
  piriformis: { name: "Piriformis", group: gluteal, description: "A deep hip rotator passing from the sacrum through the greater sciatic notch.", origin: "Anterior surface of sacral segments S2–S4 and the adjacent sacrotuberous ligament.", insertion: "Superior border of the greater trochanter.", action: "Laterally rotates the extended hip and abducts the flexed hip.", innervation: "Nerve to piriformis, usually ventral rami of S1–S2.", bloodSupply: "Superior and inferior gluteal and internal pudendal arteries.", references: [loyola, ncbiPiriformis] },
  popliteus: { name: "Popliteus", group: "Deep posterior knee", description: "A small deep muscle that initiates knee flexion by unlocking the joint.", origin: "Lateral aspect of the lateral femoral condyle and adjacent lateral meniscus.", insertion: "Posterior proximal tibia superior to the soleal line.", action: "Weakly flexes the knee and internally rotates the tibia (or laterally rotates the femur) to unlock it.", innervation: "Tibial nerve (L4–S1).", bloodSupply: "Inferior medial and lateral genicular arteries.", references: [loyola, ncbiPopliteus] },
};

export default upperLegFacts;