import type { Structure } from "../../data";
import type { NeurovascularFact } from "../../neurovascularFacts";

/** Concise, source-backed metadata for non-muscle structures in the upper-leg packs. */
const source = (title: string, url: string) => ({ title, url });
const bones = source("OpenStax · Bones of the lower limb", "https://openstax.org/books/anatomy-and-physiology/pages/8-4-bones-of-the-lower-limb");
const knee = source("NCBI Bookshelf · Anatomy of the knee", "https://www.ncbi.nlm.nih.gov/books/NBK500017/");
const hip = source("NCBI Bookshelf · Hip joint", "https://www.ncbi.nlm.nih.gov/books/NBK470555/");
const pelvis = source("NCBI Bookshelf · Ilium, ischium and pubis", "https://www.ncbi.nlm.nih.gov/books/NBK519524/");
const meniscus = source("NCBI Bookshelf · Medial meniscus", "https://www.ncbi.nlm.nih.gov/books/NBK537276/");
const lateralMeniscus = source("NCBI Bookshelf · Lateral meniscus", "https://www.ncbi.nlm.nih.gov/books/NBK519494/");
const fascia = source("NCBI Bookshelf · Fascia lata", "https://www.ncbi.nlm.nih.gov/books/NBK557497/");
const itb = source("NCBI Bookshelf · Iliotibial band tract", "https://www.ncbi.nlm.nih.gov/books/NBK537097/");
const arteries = source("UAMS · Arteries of the lower limb", "https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/artery-tables/arteries-of-the-lower-limb/");
const veins = source("UAMS · Selected veins of the lower limb", "https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/vein-tables/selected-veins-of-the-lower-limb/");
const nerves = source("UAMS · Nerves of the lower limb", "https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/nerve-tables/nerves-of-the-lower-limb/");

const fact = (reference: NeurovascularFact["source"], text: string): NeurovascularFact => ({ text, source: reference });
function record(name: string, description: string, role: string, connection: string, references: { title: string; url: string }[], facts: NeurovascularFact[] = []): Partial<Structure> {
  const value: Partial<Structure> = { name, description, role, connection, references };
  if (facts.length) value.facts = facts;
  return value;
}

export const upperLegSupportFacts: Record<string, Partial<Structure>> = {
  "hip-bone": record("Hip bone", "The fused ilium, ischium and pubis form the pelvic half of the hip joint.", "Forms the acetabulum and transfers trunk load to the lower limb.", "Acetabulum ↔ head of femur; sacroiliac joint ↔ sacrum.", [bones, pelvis]),
  femur: record("Femur", "The long bone of the thigh, with a proximal head and distal condyles.", "Transmits load between the hip and knee and provides major muscle leverage.", "Head ↔ acetabulum; condyles ↔ tibia; patellar surface ↔ patella.", [bones]),
  patella: record("Patella", "The largest sesamoid bone, embedded in the quadriceps tendon at the front of the knee.", "Improves quadriceps leverage and protects the anterior knee joint surface.", "Patellar surface of femur ↔ posterior patella; patellar ligament ↔ tibial tuberosity.", [bones, knee]),
  tibia: record("Tibia", "The large medial bone below the knee, with condyles that receive the femur.", "Bears most lower-leg load and forms the medial side of the knee.", "Medial and lateral condyles ↔ femur; proximal tibia ↔ menisci.", [bones, knee]),
  fibula: record("Fibula", "The slender lateral leg bone whose head provides attachments at the posterolateral knee.", "Provides muscle and ligament attachment and lateral knee support.", "Fibular head ↔ fibular collateral and popliteofibular ligaments; proximal tibiofibular joint.", [bones, knee]),
  sacrum: record("Sacrum", "The triangular fused bone at the base of the spine and posterior wall of the pelvis.", "Transfers axial load through the sacroiliac joints and provides origins for deep hip muscles.", "Sacroiliac joints ↔ hip bones; anterior sacrum ↔ piriformis attachments.", [pelvis]),

  "anterior-cruciate-ligament": record("Anterior cruciate ligament", "An intra-articular knee ligament running from the lateral femoral condyle to the anterior tibial intercondylar region.", "Limits anterior translation of the tibia and contributes rotational knee stability.", "Posteromedial lateral femoral condyle ↔ anterior intercondylar tibia.", [knee]),
  "posterior-cruciate-ligament": record("Posterior cruciate ligament", "The stronger central knee ligament extending from the medial femoral condyle to the posterior tibia.", "Limits posterior translation of the tibia and guides knee motion.", "Anterolateral medial femoral condyle ↔ posterior intercondylar tibia.", [knee]),
  "fibular-collateral-ligament": record("Fibular collateral ligament", "A cord-like lateral knee ligament running from the lateral femoral epicondyle to the fibular head.", "Resists varus opening and supports the posterolateral knee.", "Lateral femur ↔ fibular head; separate from the knee capsule.", [knee]),
  "superficial-part-of-tibial-collateral-ligament": record("Superficial part of tibial collateral ligament", "The broad superficial medial collateral band spanning the medial knee.", "Resists valgus stress and supports the medial knee during flexion and extension.", "Medial femoral epicondyle ↔ medial proximal tibia.", [knee]),
  "deep-part-of-tibial-collateral-ligament": record("Deep part of tibial collateral ligament", "The deep capsular portion of the medial collateral complex.", "Reinforces the medial capsule and helps stabilize the medial meniscus and knee.", "Medial femur ↔ medial meniscus and proximal tibia within the capsule.", [knee, meniscus]),
  "patellar-ligament": record("Patellar ligament", "The dense continuation of the quadriceps extensor mechanism below the patella.", "Transmits quadriceps force to extend the knee.", "Apex of patella ↔ tibial tuberosity.", [bones, knee]),
  "oblique-popliteal-ligament": record("Oblique popliteal ligament", "A posterior expansion of the semimembranosus tendon that reinforces the knee capsule.", "Supports the posterior knee capsule and limits excessive extension.", "Posteromedial tibia ↔ posterior capsule and lateral femoral region.", [knee]),
  "arcuate-popliteal-ligament": record("Arcuate popliteal ligament", "An arched posterolateral capsular reinforcement over the popliteus region.", "Reinforces the posterolateral corner of the knee.", "Fibular head ↔ posterior capsule over popliteus.", [knee]),
  "popliteofibular-ligament": record("Popliteofibular ligament", "A posterolateral knee band connecting the fibular head with the popliteus complex.", "Contributes to posterolateral and rotational knee stability.", "Fibular head ↔ popliteus tendon and posterolateral capsule.", [knee]),
  "transverse-ligament-of-knee": record("Transverse ligament of knee", "A slender anterior band connecting the anterior horns of the menisci.", "Coordinates the anterior meniscal margins during knee motion.", "Anterior horn of medial meniscus ↔ anterior horn of lateral meniscus.", [knee, meniscus]),
  "meniscopatellar-ligament": record("Meniscopatellar ligament", "Anterior capsular fibers linking the menisci to the margins of the patella.", "Helps retain the anterior meniscal edges relative to the patella.", "Anterior meniscal margins ↔ medial and lateral patellar borders.", [knee]),
  "articular-capsule-of-knee-joint": record("Articular capsule of knee joint", "A fibrous envelope surrounding the synovial knee joint and its recesses.", "Contains the joint and contributes passive knee stability.", "Femur and patella ↔ tibia, enclosing the tibiofemoral and patellofemoral spaces.", [knee]),
  "articular-capsule-of-hip-joint": record("Articular capsule of hip joint", "A strong fibrous sleeve enclosing the ball-and-socket hip joint.", "Contains the synovial joint and guides stable hip motion.", "Acetabular rim ↔ femoral neck, reinforced by iliofemoral, pubofemoral and ischiofemoral ligaments.", [hip]),
  "descending-part-of-iliofemoral-ligament": record("Descending part of iliofemoral ligament", "The inferior limb of the Y-shaped anterior hip ligament.", "Resists hip hyperextension and contributes anterior joint stability.", "Anterior inferior iliac spine region ↔ inferior intertrochanteric femur.", [hip]),
  "transverse-part-of-iliofemoral-ligament": record("Transverse part of iliofemoral ligament", "The superior limb of the Y-shaped anterior hip ligament.", "Reinforces the anterior capsule and limits extension and external rotation.", "Anterior inferior iliac spine region ↔ superior intertrochanteric femur.", [hip]),
  "ischiofemoral-ligament": record("Ischiofemoral ligament", "A posterior hip-capsule thickening spiraling from the ischial acetabular region toward the femoral neck.", "Limits excessive extension and internal rotation of the hip.", "Posterior acetabular ischium ↔ femoral neck and greater-trochanter region.", [hip, pelvis]),
  "pubofemoral-ligament": record("Pubofemoral ligament", "An anteroinferior hip-capsule thickening extending from the pubic side of the acetabulum.", "Limits excessive abduction and extension of the hip.", "Pubic acetabular rim ↔ anterior/inferior capsule and femoral neck.", [hip, pelvis]),
  "ligament-of-head-of-femur": record("Ligament of head of femur", "An intracapsular band from the acetabular notch and transverse ligament to the fovea of the femoral head.", "Provides a small adult stabilizing role and carries the foveal artery, especially relevant in childhood.", "Acetabular notch ↔ fovea capitis of femur.", [hip, pelvis]),
  "transverse-acetabular-ligament": record("Transverse acetabular ligament", "A strong continuation of the acetabular labrum bridging the inferior acetabular notch.", "Completes the acetabular rim and helps retain the femoral head.", "Anterior acetabular rim ↔ posterior acetabular rim across the notch.", [pelvis, hip]),
  "zona-orbicularis": record("Zona orbicularis", "Circular fibers in the deep hip capsule that encircle the femoral neck.", "Acts as a capsular locking ring that resists distraction of the femoral head.", "Circular capsule around the femoral neck.", [hip]),

  "fascia-lata": record("Fascia lata", "The deep investing fascia surrounding the muscles of the thigh.", "Forms fascial compartments and contributes to lateral thigh and knee stability.", "Iliac crest, inguinal and pubic attachments ↔ thigh fascia and iliotibial tract.", [fascia]),
  "iliotibial-tract": record("Iliotibial tract", "A thickened lateral part of the fascia lata receiving fibers from tensor fasciae latae and gluteus maximus.", "Transfers lateral hip muscle tension and helps stabilize the lateral knee.", "Iliac crest and gluteal fascia ↔ lateral tibia at Gerdy tubercle.", [itb, fascia]),
  "lateral-femoral-intermuscular-septum": record("Lateral femoral intermuscular septum", "A deep fascial partition extending from fascia lata to the lateral femur.", "Separates lateral/anterior and posterior thigh muscle planes and provides femoral attachment surfaces.", "Fascia lata ↔ linea aspera and lateral supracondylar femur.", [fascia]),
  "medial-femoral-intermuscular-septum": record("Medial femoral intermuscular septum", "A medial fascial partition extending from fascia lata toward the femur.", "Separates medial thigh muscle planes and helps organize the adductor compartment.", "Medial fascia lata ↔ linea aspera and medial femoral shaft.", [fascia]),

  "medial-meniscus": record("Medial meniscus", "A C-shaped fibrocartilage pad on the medial tibial plateau.", "Distributes load, deepens the tibial surface and contributes to knee stability.", "Medial tibial plateau ↔ capsule and deep medial collateral ligament; anterior and posterior horns attach to tibia.", [meniscus, knee]),
  "lateral-meniscus": record("Lateral meniscus", "A more nearly circular fibrocartilage pad on the lateral tibial plateau.", "Distributes load and improves congruence of the lateral knee compartment.", "Lateral tibial plateau ↔ capsule and tibial intercondylar attachments; more mobile than the medial meniscus.", [lateralMeniscus, knee]),
  "acetabular-labrum": record("Acetabular labrum", "A fibrocartilaginous rim around the acetabulum that deepens the hip socket.", "Improves femoral-head containment and contributes to a fluid seal around the joint.", "Acetabular rim ↔ capsule and transverse acetabular ligament.", [hip, pelvis]),

  "femoral-artery": record("Femoral artery", "The principal arterial trunk of the thigh, continuing from the external iliac artery below the inguinal ligament.", "Supplies the anterior thigh and gives branches to the deep thigh and knee networks.", "External iliac artery ↔ adductor hiatus, where it continues as popliteal artery.", [arteries], [fact(arteries, "Passes beneath the inguinal ligament and continues through the thigh toward the adductor hiatus."), fact(arteries, "Gives rise to the deep femoral and circumflex femoral systems.")]),
  "deep-femoral-artery": record("Deep femoral artery", "The major deep branch of the femoral artery supplying the deep thigh.", "Supplies much of the medial and posterior thigh through circumflex and perforating branches.", "Femoral artery ↔ profunda femoris branches around and through the thigh muscles.", [arteries], [fact(arteries, "Gives rise to the medial and lateral circumflex femoral arteries and perforating arteries.")]),
  "lateral-circumflex-femoral-artery": record("Lateral circumflex femoral artery", "A circumflex branch that runs laterally around the proximal femur.", "Supplies the lateral thigh, hip and parts of the quadriceps.", "Usually deep femoral artery ↔ ascending, transverse and descending branches.", [arteries], [fact(arteries, "Has ascending, transverse and descending branches; its origin can vary from the femoral artery.")]),
  "medial-circumflex-femoral-artery": record("Medial circumflex femoral artery", "A circumflex branch that winds toward the medial and posterior hip.", "Supplies medial thigh structures and contributes to vascular supply around the femoral neck.", "Usually deep femoral artery ↔ medial hip and proximal femur.", [arteries], [fact(arteries, "Has ascending and descending branches and may arise directly from the femoral artery.")]),
  "perforating-femoral-arteries": record("Perforating femoral arteries", "Branches of the deep femoral artery that pass through the adductor region.", "Supply the posterior and medial thigh and participate in collateral circulation.", "Deep femoral artery ↔ adductor magnus and posterior thigh tissues.", [arteries], [fact(arteries, "Perforating branches cross the adductor magnus to reach posterior thigh structures.")]),
  "popliteal-artery": record("Popliteal artery", "The continuation of the femoral artery behind the knee.", "Supplies the knee through genicular branches and divides into leg arteries distally.", "Adductor hiatus ↔ popliteal fossa and proximal tibial/anterior tibial branches.", [arteries], [fact(arteries, "Gives genicular branches around the knee and continues toward the tibial arterial system.")]),
  "superior-lateral-genicular-artery": record("Superior lateral genicular artery", "A genicular branch running above the lateral femoral condyle.", "Contributes to the arterial network around the knee.", "Popliteal artery ↔ lateral supracondylar knee and patellar anastomosis.", [arteries], [fact(arteries, "Anastomoses with neighboring genicular and descending femoral branches around the knee.")]),
  "superior-medial-genicular-artery": record("Superior medial genicular artery", "A genicular branch running above the medial femoral condyle.", "Contributes to the medial knee and patellar arterial network.", "Popliteal artery ↔ medial supracondylar knee and patellar anastomosis.", [arteries], [fact(arteries, "Participates in the genicular anastomosis around the medial knee.")]),
  "inferior-lateral-genicular-artery": record("Inferior lateral genicular artery", "A genicular branch passing below the lateral femoral condyle.", "Supplies the lateral knee capsule and adjacent structures.", "Popliteal artery ↔ lateral tibial plateau and patellar network.", [arteries], [fact(arteries, "Anastomoses with other genicular branches around the knee joint.")]),
  "inferior-medial-genicular-artery": record("Inferior medial genicular artery", "A genicular branch passing below the medial femoral condyle.", "Supplies the medial knee capsule and adjacent proximal tibia.", "Popliteal artery ↔ medial tibial plateau and patellar network.", [arteries], [fact(arteries, "Anastomoses with superior and opposite-side genicular branches.")]),
  "middle-genicular-artery": record("Middle genicular artery", "A small branch entering the central knee capsule.", "Supplies intra-articular knee structures, including cruciate ligament regions.", "Popliteal artery ↔ intercondylar notch and synovial knee tissues.", [arteries], [fact(arteries, "Pierces the posterior capsule to reach central intra-articular structures.")]),
  "patellar-anastomosis": record("Patellar anastomosis", "A periarticular arterial network around the patella and anterior knee.", "Maintains collateral arterial connections around the knee.", "Genicular and descending femoral branches ↔ anterior knee and patellar tissues.", [arteries], [fact(arteries, "Receives contributions from superior and inferior genicular and descending femoral branches.")]),

  "femoral-vein": record("Femoral vein", "The principal deep vein of the thigh accompanying the femoral artery.", "Returns blood from the deep thigh and receives superficial and deep tributaries.", "Popliteal vein ↔ external iliac vein above the inguinal ligament.", [veins], [fact(veins, "Receives the great saphenous vein and deep femoral venous drainage before becoming external iliac vein.")]),
  "deep-femoral-vein": record("Deep femoral vein", "The deep venous companion of the profunda femoris artery.", "Drains deep thigh muscles and receives perforating and circumflex tributaries.", "Deep thigh veins ↔ femoral vein.", [veins], [fact(veins, "Accompanies the deep femoral artery and communicates with femoral venous drainage.")]),
  "lateral-circumflex-femoral-veins": record("Lateral circumflex femoral veins", "Small veins accompanying the lateral circumflex femoral artery and its branches.", "Drain the lateral proximal thigh and hip region.", "Lateral circumflex femoral territory ↔ deep femoral or femoral vein.", [veins]),
  "medial-circumflex-femoral-veins": record("Medial circumflex femoral veins", "Veins accompanying the medial circumflex femoral artery around the proximal femur.", "Drain the medial and posterior hip and proximal thigh.", "Medial circumflex femoral territory ↔ deep femoral or femoral vein.", [veins]),
  "perforating-veins": record("Perforating veins", "Deep veins accompanying perforating arteries through the adductor region.", "Drain posterior and medial thigh muscle territories.", "Posterior thigh venous plexus ↔ deep femoral vein.", [veins]),
  "popliteal-vein": record("Popliteal vein", "The deep vein in the popliteal fossa formed by convergence of leg veins.", "Returns blood from the leg and knee to the femoral vein.", "Proximal leg veins ↔ femoral vein through the adductor hiatus.", [veins], [fact(veins, "Receives genicular tributaries and the small saphenous vein before continuing as the femoral vein.")]),
  "great-saphenous-vein": record("Great saphenous vein", "The long superficial vein ascending on the medial side of the lower limb.", "Drains superficial medial foot, leg and thigh territories.", "Medial foot and leg ↔ femoral vein at the saphenofemoral junction.", [veins]),
  "small-saphenous-vein": record("Small saphenous vein", "A superficial vein ascending behind the lateral malleolus and through the posterior calf.", "Drains superficial lateral foot and posterior leg territories.", "Dorsal/lateral foot ↔ popliteal vein in the popliteal fossa.", [veins]),
  "genicular-veins": record("Genicular veins", "Small veins accompanying the genicular arteries around the knee.", "Drain the knee capsule and periarticular tissues.", "Periarticular knee network ↔ popliteal vein.", [veins]),

  "femoral-nerve": record("Femoral nerve", "The largest branch of the lumbar plexus, passing beneath the inguinal ligament into the anterior thigh.", "Provides motor supply to anterior-thigh muscles and sensory branches to the anterior thigh and medial leg.", "Lumbar plexus ↔ anterior thigh and saphenous nerve.", [nerves], [fact(nerves, "Arises from ventral rami L2–L4 and supplies sartorius, quadriceps and pectineus branches."), fact(nerves, "The saphenous nerve is its long sensory continuation toward the medial leg and foot.")]),
  "sciatic-nerve": record("Sciatic nerve", "The large sacral-plexus nerve descending through the posterior hip and thigh.", "Supplies the hamstrings through tibial and common fibular divisions and continues to the leg.", "Sacral plexus ↔ posterior thigh, tibial nerve and common fibular nerve.", [nerves], [fact(nerves, "Is composed of tibial and common fibular divisions and has no direct named muscular branch in the thigh table."), fact(nerves, "Its branches supply semitendinosus, semimembranosus, biceps femoris and the hamstring portion of adductor magnus.")]),
  "obturator-nerve": record("Obturator nerve", "A lumbar plexus nerve passing through the obturator canal into the medial thigh.", "Supplies most medial-thigh adductors and sensation over the lower medial thigh.", "Lumbar plexus ↔ anterior and posterior obturator branches.", [nerves], [fact(nerves, "Arises from ventral rami L2–L4 and supplies adductor longus, adductor brevis, adductor magnus, gracilis and obturator externus."), fact(nerves, "Divides into anterior and posterior branches around adductor brevis.")]),
  "anterior-branch-of-obturator-nerve": record("Anterior branch of obturator nerve", "The anterior division of the obturator nerve in the medial thigh.", "Carries motor fibers to anterior medial-thigh adductors and sensory fibers to the medial thigh.", "Obturator nerve ↔ adductor longus/brevis and gracilis region.", [nerves], [fact(nerves, "Branches from the obturator nerve after it passes through the obturator canal.")]),
  "posterior-branch-of-obturator-nerve": record("Posterior branch of obturator nerve", "The posterior division of the obturator nerve passing deep to adductor brevis.", "Supplies deeper medial-thigh muscles, including obturator externus and portions of adductor magnus.", "Obturator nerve ↔ deep adductor compartment.", [nerves], [fact(nerves, "Is the deep division associated with motor supply to obturator externus and adductor magnus portions.")]),
  "lateral-femoral-cutaneous-nerve": record("Lateral femoral cutaneous nerve", "A sensory nerve from the lumbar plexus crossing toward the lateral thigh.", "Provides cutaneous sensation to the lateral thigh.", "Lumbar plexus (L2–L3) ↔ anterior and posterior lateral-thigh branches.", [nerves], [fact(nerves, "Has anterior and posterior branches and carries no motor supply to thigh muscles.")]),
  "posterior-femoral-cutaneous-nerve": record("Posterior femoral cutaneous nerve", "A sensory branch of the sacral plexus descending in the posterior thigh.", "Provides sensation to the lower buttock and posterior thigh.", "Sacral plexus (S1–S3) ↔ inferior cluneal and perineal branches.", [nerves], [fact(nerves, "Its inferior cluneal branches supply skin of the lower buttock and its main cutaneous territory is the posterior thigh.")]),
  "anterior-cutaneous-branches-of-femoral-nerve": record("Anterior cutaneous branches of femoral nerve", "Superficial sensory branches of the femoral nerve in the anterior thigh.", "Carry cutaneous sensation from the anterior thigh.", "Femoral nerve ↔ skin of anterior thigh.", [nerves], [fact(nerves, "Are cutaneous branches of the femoral nerve rather than motor branches to the quadriceps.")]),
  "saphenous-nerve": record("Saphenous nerve", "The terminal sensory branch of the femoral nerve descending along the medial knee and leg.", "Provides sensation to the medial leg and medial foot.", "Femoral nerve ↔ infrapatellar and medial crural branches.", [nerves], [fact(nerves, "Passes anterior to the medial malleolus and does not pass through the adductor hiatus."), fact(nerves, "Travels with the great saphenous vein near the medial ankle.")]),
  "tibial-nerve": record("Tibial nerve", "The medial division of the sciatic nerve descending through the posterior thigh and popliteal fossa.", "Supplies hamstrings, posterior leg and plantar foot muscles and sensation to the plantar foot.", "Sciatic nerve ↔ posterior thigh, popliteal fossa and posterior leg.", [nerves], [fact(nerves, "Supplies semimembranosus, semitendinosus, long head of biceps femoris and hamstring adductor magnus."), fact(nerves, "Continues behind the medial malleolus toward the plantar nerves.")]),
  "common-fibular-nerve": record("Common fibular nerve", "The lateral division of the sciatic nerve winding around the fibular neck.", "Continues as superficial and deep fibular nerves to supply the lateral and anterior leg.", "Sciatic nerve ↔ fibular neck, superficial fibular nerve and deep fibular nerve.", [nerves], [fact(nerves, "Divides into superficial and deep fibular nerves near the fibular neck."), fact(nerves, "The fibular terminology is preferred to the older peroneal terminology in the UAMS table.")]),
  "superior-gluteal-nerve": record("Superior gluteal nerve", "A sacral-plexus branch passing through the greater sciatic foramen above piriformis.", "Supplies gluteus medius, gluteus minimus and tensor fasciae latae.", "Sacral plexus (L4–S1) ↔ gluteal abductor compartment.", [nerves], [fact(nerves, "Passes superior to piriformis and divides into superior and inferior branches.")]),
  "nerve-to-quadratus-femoris-muscle": record("Nerve to quadratus femoris muscle", "A sacral-plexus motor branch running anterior to the obturator internus tendon.", "Supplies quadratus femoris and inferior gemellus.", "Sacral plexus (L4–S1) ↔ deep posterior hip rotators.", [nerves], [fact(nerves, "Passes anterior to the obturator internus tendon and gives a branch to inferior gemellus.")]),
  "nerve-to-piriformis-muscle": record("Nerve to piriformis muscle", "A short sacral-plexus motor branch to piriformis.", "Supplies piriformis in the deep gluteal region.", "Sacral plexus ↔ piriformis muscle.", [nerves], [fact(nerves, "Arises from sacral ventral rami, typically S1–S2, in the lumbosacral plexus distribution.")]),
};

export default upperLegSupportFacts;